### ISSUE TITLE
What are the differences between  terminus and qemu for rv64? How to update terminus for softs can run on qemu?

### ISSUE THREAD

**Issue by chyyuu** [shady831213/terminus#1]
I tested rustsbi, xv6, rcore-tutorial on qemu-system-riscv64 5.0.0 successfully.
But I can not run this softs on terminus using elf format files of rustsbi, xv6?

How to update terminus for softs can run on qemu? 

Thanks!

**Comment by shady831213** [comment]
Hi,
The device model in terminus is different from qemu. For rustsbi, you can refefer to [terminus_bl](https://github.com/shady831213/terminus_bl). I have used rustsbi to boot linux successfully.Please note it's only support single core for now, SMP is still WIP.
Best Regards.
